apiVersion: v1
kind: Service
metadata:
  name: {{ include "tweet-service-graphql-nodejs.fullname" . }}
  labels:
    {{- include "tweet-service-graphql-nodejs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5001
      protocol: TCP
      name: http
  selector:
    {{- include "tweet-service-graphql-nodejs.selectorLabels" . | nindent 4 }}
